"""Post-hoc affine calibration under a train-versus-test density ratio.

This reproduces the method the N283T challenge report describes, which is a
different experiment from fitting a monotone map on one held-out partition and
is deliberately not that. Three pieces:

Out-of-fold predictions. The map is fitted against predictions the model did
not train on, generated by k-fold cross-validation over the whole fit set
rather than by holding out a single slice. Every fit compound therefore
contributes one prediction made without it.

A density ratio as a per-compound weight. A classifier on Morgan fingerprints
is trained to separate the fit compounds from the test compounds, and each fit
compound's weight is ``P(test|x) / (1 - P(test|x))``. Compounds that look like
the test set count for more, which is what tilts the map toward the
distribution it will be applied to. The report calls clipping essential, "too
strong a classifier lets a handful of test-like compounds pull the fit", and
clips to [1/3, 3]; that bound is the default here.

An affine map. ``calibrated = slope * raw + intercept``, fitted by weighted
least squares. It is affine rather than monotone-but-arbitrary because the
quantity being corrected is scale and offset, and because a positive slope
leaves every ranking metric untouched: only the error metrics can move.

Nothing here reads a test label. The test compounds enter through their
structures alone, as the classifier's positive class, which is what makes the
method legitimate to apply to a blinded set.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any

import numpy as np
from numpy.typing import NDArray
from rdkit import Chem, RDLogger
from rdkit.Chem import rdFingerprintGenerator
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import KFold

logger = logging.getLogger(__name__)

# the report leaves the fingerprint unspecified; these are the conventional
# defaults, and they are recorded in every calibration record rather than
# assumed to be obvious
MORGAN_RADIUS = 2
MORGAN_BITS = 2048

# the report's own bound, quoted: "clipped to [1/3, 3]"
WEIGHT_CLIP = (1.0 / 3.0, 3.0)

# folds the out-of-fold predictions are generated over
N_FOLDS = 5

# a deliberately weak separator. The report warns that too strong a classifier
# lets a few test-like compounds dominate, so this is a linear model with
# ordinary regularisation rather than anything that can memorise a fingerprint
CLASSIFIER_C = 1.0

RDLogger.DisableLog("rdApp.*")  # pyright: ignore[reportAttributeAccessIssue]


class CalibrationError(ValueError):
    """A calibration could not be fitted from what it was given."""


@dataclass(frozen=True)
class AffineCalibration:
    """A fitted affine map and the evidence behind it.

    Attributes
    ----------
    slope, intercept : float
        ``calibrated = slope * raw + intercept``.
    n_fit : int
        Out-of-fold predictions the map was fitted on.
    weight_summary : dict
        Minimum, median, maximum and clipped fraction of the density-ratio
        weights, which is what says whether the ratio did anything.
    classifier_auc : float
        In-sample ROC AUC of the train-versus-test separator. A value near 0.5
        means the two sets are indistinguishable on this fingerprint, and the
        weights are then all near 1 and the calibration is unweighted in
        everything but name.
    """

    slope: float
    intercept: float
    n_fit: int
    weight_summary: dict[str, float]
    classifier_auc: float

    def apply(self, predictions: NDArray[np.float64]) -> NDArray[np.float64]:
        """Return the calibrated predictions.

        Parameters
        ----------
        predictions : ndarray
            Raw predictions, in the same units the map was fitted on.

        Returns
        -------
        ndarray
            ``slope * predictions + intercept``.
        """
        return self.slope * np.asarray(predictions, dtype=np.float64) + self.intercept

    def as_dict(self) -> dict[str, Any]:
        """Return the map and its evidence as plain data for a record."""
        return {
            "slope": self.slope,
            "intercept": self.intercept,
            "n_fit": self.n_fit,
            "weights": self.weight_summary,
            "classifier_auc": self.classifier_auc,
        }


def morgan_matrix(
    smiles: list[str], *, radius: int = MORGAN_RADIUS, n_bits: int = MORGAN_BITS
) -> NDArray[np.float64]:
    """Return a Morgan fingerprint matrix, one row per molecule.

    Parameters
    ----------
    smiles : list of str
        Molecules to featurize.
    radius : int, optional
        Morgan radius. Defaults to :data:`MORGAN_RADIUS`.
    n_bits : int, optional
        Fingerprint length. Defaults to :data:`MORGAN_BITS`.

    Returns
    -------
    ndarray
        Shape ``(len(smiles), n_bits)``, entries 0 or 1.

    Raises
    ------
    CalibrationError
        If any SMILES does not parse, since a silently dropped molecule would
        misalign the weights against the predictions they multiply.
    """
    generator = rdFingerprintGenerator.GetMorganGenerator(radius=radius, fpSize=n_bits)
    rows = np.zeros((len(smiles), n_bits), dtype=np.float64)
    for i, smi in enumerate(smiles):
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            raise CalibrationError(f"could not parse SMILES at row {i}: {smi!r}")
        rows[i] = np.asarray(generator.GetFingerprintAsNumPy(mol), dtype=np.float64)
    return rows


def density_ratio_weights(
    fit_smiles: list[str],
    test_smiles: list[str],
    *,
    radius: int = MORGAN_RADIUS,
    n_bits: int = MORGAN_BITS,
    clip: tuple[float, float] = WEIGHT_CLIP,
    seed: int = 0,
) -> tuple[NDArray[np.float64], float]:
    """Weight each fit compound by how test-like it is.

    A logistic regression on Morgan fingerprints separates the two sets, and
    each fit compound's weight is ``P(test|x) / (1 - P(test|x))``, clipped.
    Only the test compounds' structures are used; no test label is read.

    Parameters
    ----------
    fit_smiles, test_smiles : list of str
        The two sets, as canonical SMILES.
    radius, n_bits : int, optional
        Fingerprint settings.
    clip : tuple of float, optional
        Lower and upper bound on the weights. Defaults to
        :data:`WEIGHT_CLIP`, the report's own bound.
    seed : int, optional
        Seed for the classifier.

    Returns
    -------
    weights : ndarray
        One weight per fit compound, in the order given.
    auc : float
        In-sample ROC AUC of the separator, as a check on whether the ratio is
        carrying information or the two sets are indistinguishable.

    Raises
    ------
    CalibrationError
        If either set is empty, or the bounds are not a positive interval.
    """
    if not fit_smiles or not test_smiles:
        raise CalibrationError("both the fit and test sets must be non-empty")
    low, high = clip
    if not 0 < low <= high:
        raise CalibrationError(f"clip must be a positive interval, got {clip!r}")

    x = np.vstack(
        [
            morgan_matrix(fit_smiles, radius=radius, n_bits=n_bits),
            morgan_matrix(test_smiles, radius=radius, n_bits=n_bits),
        ]
    )
    y = np.concatenate([np.zeros(len(fit_smiles)), np.ones(len(test_smiles))])

    # the classes are strongly imbalanced here, 4,392 against 260, and an
    # unbalanced fit would push every probability toward zero and every weight
    # to the lower clip. Balancing makes the ratio a statement about which
    # compounds look test-like rather than about how few test compounds exist
    model = LogisticRegression(
        C=CLASSIFIER_C, max_iter=2000, class_weight="balanced", random_state=seed
    )
    model.fit(x, y)

    auc = float(roc_auc_score(y, model.predict_proba(x)[:, 1]))

    probability = model.predict_proba(x[: len(fit_smiles)])[:, 1]
    # guard the ratio against a probability of exactly one, which the clip
    # would otherwise never see because the division diverges first
    probability = np.clip(probability, 1e-6, 1 - 1e-6)
    weights = np.clip(probability / (1.0 - probability), low, high)
    return weights, auc


def fit_affine(
    out_of_fold: NDArray[np.float64],
    observed: NDArray[np.float64],
    weights: NDArray[np.float64] | None = None,
) -> tuple[float, float]:
    """Fit ``observed ~ slope * out_of_fold + intercept`` by weighted least squares.

    Parameters
    ----------
    out_of_fold : ndarray
        Predictions made by a model that did not train on the compound.
    observed : ndarray
        True labels, aligned with them.
    weights : ndarray or None, optional
        Per-compound weights. None fits unweighted, which is the ablation the
        density ratio is measured against.

    Returns
    -------
    slope, intercept : float

    Raises
    ------
    CalibrationError
        If the inputs disagree in length, hold fewer than two points, or the
        predictions are constant, which leaves the slope undetermined.
    """
    pred = np.asarray(out_of_fold, dtype=np.float64)
    truth = np.asarray(observed, dtype=np.float64)
    if pred.shape != truth.shape:
        raise CalibrationError(f"shape mismatch: {pred.shape} predictions, {truth.shape} labels")
    if pred.size < 2:
        raise CalibrationError("an affine map needs at least two points")
    if np.allclose(pred, pred[0]):
        raise CalibrationError("predictions are constant, so the slope is undetermined")

    w = np.ones_like(pred) if weights is None else np.asarray(weights, dtype=np.float64)
    if w.shape != pred.shape:
        raise CalibrationError(f"shape mismatch: {w.shape} weights, {pred.shape} predictions")

    design = np.column_stack([pred, np.ones_like(pred)])
    root = np.sqrt(w)
    solution, *_ = np.linalg.lstsq(design * root[:, None], truth * root, rcond=None)
    return float(solution[0]), float(solution[1])


def summarize_weights(weights: NDArray[np.float64], clip: tuple[float, float]) -> dict[str, float]:
    """Return the weight distribution and how much of it the clip bound."""
    low, high = clip
    at_bound = np.isclose(weights, low) | np.isclose(weights, high)
    return {
        "min": float(weights.min()),
        "median": float(np.median(weights)),
        "max": float(weights.max()),
        "mean": float(weights.mean()),
        "clipped_fraction": float(at_bound.mean()),
    }


def calibrate(
    out_of_fold: NDArray[np.float64],
    observed: NDArray[np.float64],
    fit_smiles: list[str],
    test_smiles: list[str],
    *,
    radius: int = MORGAN_RADIUS,
    n_bits: int = MORGAN_BITS,
    clip: tuple[float, float] = WEIGHT_CLIP,
    weighted: bool = True,
    seed: int = 0,
) -> AffineCalibration:
    """Fit the report's affine map from out-of-fold predictions.

    Parameters
    ----------
    out_of_fold : ndarray
        One prediction per fit compound, made without that compound.
    observed : ndarray
        True labels for the fit compounds.
    fit_smiles, test_smiles : list of str
        Canonical SMILES for both sets, the fit list aligned with the arrays.
    radius, n_bits, clip, seed : optional
        Passed to :func:`density_ratio_weights`.
    weighted : bool, optional
        False fits the map unweighted, which is the ablation that says what
        the density ratio bought. Defaults to True.

    Returns
    -------
    AffineCalibration
        The map, and the evidence behind it.
    """
    if weighted:
        weights, auc = density_ratio_weights(
            fit_smiles, test_smiles, radius=radius, n_bits=n_bits, clip=clip, seed=seed
        )
    else:
        weights, auc = np.ones(len(fit_smiles)), float("nan")

    slope, intercept = fit_affine(out_of_fold, observed, weights)
    logger.info(
        "affine calibration: slope %.4f, intercept %.4f, separator AUC %.3f",
        slope,
        intercept,
        auc,
    )
    return AffineCalibration(
        slope=slope,
        intercept=intercept,
        n_fit=int(np.size(out_of_fold)),
        weight_summary=summarize_weights(weights, clip),
        classifier_auc=auc,
    )


def fold_indices(n: int, *, n_folds: int = N_FOLDS, seed: int = 0) -> list[tuple[Any, Any]]:
    """Return the train and held-out row indices for each fold.

    Shuffled with a fixed seed so the partition is a property of the seed and
    the row count rather than of the order the split file happened to be in.
    """
    if n_folds < 2:
        raise CalibrationError(f"out-of-fold predictions need at least 2 folds, got {n_folds}")
    if n_folds > n:
        raise CalibrationError(f"{n_folds} folds over {n} compounds")
    splitter = KFold(n_splits=n_folds, shuffle=True, random_state=seed)
    return list(splitter.split(np.arange(n)))
