"""Post-hoc affine calibration under a train-versus-test density ratio.

This reproduces the method the N283T challenge report describes, which is a
different experiment from fitting a monotone map on one held-out partition and
is deliberately not that. Three pieces:

Out-of-fold predictions. The map is fitted against predictions the model did
not train on, generated by k-fold cross-validation over the whole fit set
rather than by holding out a single slice. Every fit compound therefore
contributes one prediction made without it.

A density ratio as a per-compound weight. A classifier on Morgan fingerprints
is trained to separate the fit compounds from the test compounds, and each fit
compound's weight is ``P(test|x) / (1 - P(test|x))``. Compounds that look like
the test set count for more, which is what tilts the map toward the
distribution it will be applied to. The report calls clipping essential, "too
strong a classifier lets a handful of test-like compounds pull the fit", and
clips to [1/3, 3]; that bound is the default here.

A map from raw predictions to calibrated ones, fitted by weighted least
squares on those out-of-fold predictions. Three are offered, and they differ
only in how much freedom the map has:

``affine``, ``calibrated = slope * raw + intercept``, which is the report's.
The quantity it corrects is scale and offset together.

``scale``, ``calibrated = factor * raw``, the same map through the origin. It
answers whether an offset was doing the work, and cannot introduce a bias of
its own: a model already unbiased in the mean stays unbiased.

``isotonic``, any non-decreasing map, fitted on the same weighted points. It
can correct a curve the affine map cannot reach, and it is the one that can
overfit: it interpolates between the knots it saw and clips outside their
range, so a test compound predicted beyond anything in the fit set is pinned
to the end of the map.

The two affine maps are strictly increasing wherever their slope is positive,
so neither can move a ranking metric and only the error metrics can respond to
them. Isotonic is not strictly increasing: it is flat wherever the fit points
were out of order, so it maps a stretch of the range to one value and creates
ties that a rank metric can see. It is a quantisation as much as a correction,
and how coarse a one is a property of the data rather than of the method,
worth reading off a fit before trusting it.

Nothing here reads a test label. The test compounds enter through their
structures alone, as the classifier's positive class, which is what makes the
method legitimate to apply to a blinded set.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any

import numpy as np
from numpy.typing import NDArray
from rdkit import Chem, RDLogger
from rdkit.Chem import rdFingerprintGenerator
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_predict

logger = logging.getLogger(__name__)

# the report leaves the fingerprint unspecified; these are the conventional
# defaults, and they are recorded in every calibration record rather than
# assumed to be obvious
MORGAN_RADIUS = 2
MORGAN_BITS = 2048

# the report's own bound, quoted: "clipped to [1/3, 3]"
WEIGHT_CLIP = (1.0 / 3.0, 3.0)

# folds the out-of-fold predictions are generated over
N_FOLDS = 5

# a deliberately weak separator. The report warns that too strong a classifier
# lets a few test-like compounds dominate, so this is a linear model with
# ordinary regularisation rather than anything that can memorise a fingerprint
CLASSIFIER_C = 1.0

RDLogger.DisableLog("rdApp.*")  # pyright: ignore[reportAttributeAccessIssue]


class CalibrationError(ValueError):
    """A calibration could not be fitted from what it was given."""


@dataclass(frozen=True)
class AffineCalibration:
    """A fitted affine map and the evidence behind it.

    A pure scale factor is this map with a zero intercept, and is recorded as
    one rather than as a type of its own: everything reading a calibration
    wants a slope and an intercept, and a scale that had to be special-cased
    downstream would be a second thing to keep in step.

    Attributes
    ----------
    method : str
        Which map was fitted, ``affine`` or ``scale``.
    slope, intercept : float
        ``calibrated = slope * raw + intercept``.
    n_fit : int
        Out-of-fold predictions the map was fitted on.
    weight_summary : dict
        Minimum, median, maximum and clipped fraction of the density-ratio
        weights, which is what says whether the ratio did anything.
    classifier_auc : float
        Out-of-fold ROC AUC of the train-versus-test separator. Near 0.5 means
        the two sets are indistinguishable on this fingerprint and the weights
        are all near 1, leaving the calibration unweighted in everything but
        name. Near 1 means the opposite and is no better: with almost no
        overlap the ratio has nothing to grade, every fit compound is pinned at
        the lower clip, and the map is fitted on a handful of test-like
        outliers. The weight summary's clipped fraction says which has happened.
    """

    slope: float
    intercept: float
    n_fit: int
    weight_summary: dict[str, float]
    classifier_auc: float
    method: str = "affine"

    def apply(self, predictions: NDArray[np.float64]) -> NDArray[np.float64]:
        """Return the calibrated predictions.

        Parameters
        ----------
        predictions : ndarray
            Raw predictions, in the same units the map was fitted on.

        Returns
        -------
        ndarray
            ``slope * predictions + intercept``.
        """
        return self.slope * np.asarray(predictions, dtype=np.float64) + self.intercept

    def sigma_factor(self, predictions: NDArray[np.float64]) -> NDArray[np.float64]:
        """Return what this map does to a predictive spread, per prediction.

        An affine map moves the whole distribution, so its standard deviation
        scales by the absolute slope everywhere.
        """
        return np.full(np.shape(predictions), abs(self.slope), dtype=np.float64)

    def as_dict(self) -> dict[str, Any]:
        """Return the map and its evidence as plain data for a record."""
        return {
            "method": self.method,
            "slope": self.slope,
            "intercept": self.intercept,
            "n_fit": self.n_fit,
            "weights": self.weight_summary,
            "classifier_auc": self.classifier_auc,
        }


@dataclass(frozen=True)
class IsotonicCalibration:
    """A fitted non-decreasing map and the evidence behind it.

    Stored as the knots the fit produced rather than as an estimator, so a
    record holds the map itself and applying it later needs nothing but
    interpolation. Outside the knots the map is constant, which is what
    ``out_of_bounds="clip"`` means: a test compound predicted beyond anything
    in the fit set is pinned to the nearest end, and no extrapolation is
    invented for it.

    Attributes
    ----------
    method : str
        Always ``isotonic``. Carried so a record says which map it holds.
    knots_x, knots_y : tuple of float
        The fitted step function, x increasing.
    n_fit : int
        Out-of-fold predictions the map was fitted on.
    n_clipped : int
        Fit points outside the knots, which is zero by construction and is
        recomputed for the test set when the map is applied.
    weight_summary : dict
        The density-ratio weight distribution, as for the affine map.
    classifier_auc : float
        Out-of-fold ROC AUC of the train-versus-test separator.
    """

    knots_x: tuple[float, ...]
    knots_y: tuple[float, ...]
    n_fit: int
    weight_summary: dict[str, float]
    classifier_auc: float
    method: str = "isotonic"

    def apply(self, predictions: NDArray[np.float64]) -> NDArray[np.float64]:
        """Return the calibrated predictions, clipped to the fitted range."""
        raw = np.asarray(predictions, dtype=np.float64)
        return np.interp(raw, np.asarray(self.knots_x), np.asarray(self.knots_y))

    def sigma_factor(self, predictions: NDArray[np.float64]) -> NDArray[np.float64]:
        """Return what this map does to a predictive spread, per prediction.

        A monotone map is affine only locally, so the spread scales by the
        slope of the segment each prediction lands on. Where the map is flat
        the factor is zero, which is the map saying that stretch of the range
        carries no information: a spread there has been mapped to a point.
        """
        raw = np.asarray(predictions, dtype=np.float64)
        x = np.asarray(self.knots_x, dtype=np.float64)
        y = np.asarray(self.knots_y, dtype=np.float64)
        if x.size < 2:
            return np.zeros_like(raw)
        slopes = np.diff(y) / np.diff(x)
        # a prediction outside the knots sits on the clipped end, where the map
        # is constant and the spread it implies is zero
        index = np.clip(np.searchsorted(x, raw, side="right") - 1, 0, slopes.size - 1)
        factor = np.where((raw < x[0]) | (raw > x[-1]), 0.0, slopes[index])
        return np.abs(factor)

    def as_dict(self) -> dict[str, Any]:
        """Return the map and its evidence as plain data for a record."""
        return {
            "method": self.method,
            "knots_x": list(self.knots_x),
            "knots_y": list(self.knots_y),
            "n_knots": len(self.knots_x),
            "n_fit": self.n_fit,
            "weights": self.weight_summary,
            "classifier_auc": self.classifier_auc,
        }


# every fitted map, whichever method produced it
Calibration = AffineCalibration | IsotonicCalibration

# the maps this module can fit, in order of how much freedom they have
METHODS = ("affine", "scale", "isotonic")


def morgan_matrix(
    smiles: list[str], *, radius: int = MORGAN_RADIUS, n_bits: int = MORGAN_BITS
) -> NDArray[np.float64]:
    """Return a Morgan fingerprint matrix, one row per molecule.

    Parameters
    ----------
    smiles : list of str
        Molecules to featurize.
    radius : int, optional
        Morgan radius. Defaults to :data:`MORGAN_RADIUS`.
    n_bits : int, optional
        Fingerprint length. Defaults to :data:`MORGAN_BITS`.

    Returns
    -------
    ndarray
        Shape ``(len(smiles), n_bits)``, entries 0 or 1.

    Raises
    ------
    CalibrationError
        If any SMILES does not parse, since a silently dropped molecule would
        misalign the weights against the predictions they multiply.
    """
    generator = rdFingerprintGenerator.GetMorganGenerator(radius=radius, fpSize=n_bits)
    rows = np.zeros((len(smiles), n_bits), dtype=np.float64)
    for i, smi in enumerate(smiles):
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            raise CalibrationError(f"could not parse SMILES at row {i}: {smi!r}")
        rows[i] = np.asarray(generator.GetFingerprintAsNumPy(mol), dtype=np.float64)
    return rows


def density_ratio_weights(
    fit_smiles: list[str],
    test_smiles: list[str],
    *,
    radius: int = MORGAN_RADIUS,
    n_bits: int = MORGAN_BITS,
    clip: tuple[float, float] = WEIGHT_CLIP,
    seed: int = 0,
) -> tuple[NDArray[np.float64], float]:
    """Weight each fit compound by how test-like it is.

    A logistic regression on Morgan fingerprints separates the two sets, and
    each fit compound's weight is ``P(test|x) / (1 - P(test|x))``, clipped.
    Only the test compounds' structures are used; no test label is read.

    Parameters
    ----------
    fit_smiles, test_smiles : list of str
        The two sets, as canonical SMILES.
    radius, n_bits : int, optional
        Fingerprint settings.
    clip : tuple of float, optional
        Lower and upper bound on the weights. Defaults to
        :data:`WEIGHT_CLIP`, the report's own bound.
    seed : int, optional
        Seed for the classifier.

    Returns
    -------
    weights : ndarray
        One weight per fit compound, in the order given.
    auc : float
        In-sample ROC AUC of the separator, as a check on whether the ratio is
        carrying information or the two sets are indistinguishable.

    Raises
    ------
    CalibrationError
        If either set is empty, or the bounds are not a positive interval.
    """
    if not fit_smiles or not test_smiles:
        raise CalibrationError("both the fit and test sets must be non-empty")
    low, high = clip
    if not 0 < low <= high:
        raise CalibrationError(f"clip must be a positive interval, got {clip!r}")

    x = np.vstack(
        [
            morgan_matrix(fit_smiles, radius=radius, n_bits=n_bits),
            morgan_matrix(test_smiles, radius=radius, n_bits=n_bits),
        ]
    )
    y = np.concatenate([np.zeros(len(fit_smiles)), np.ones(len(test_smiles))])

    # the classes are strongly imbalanced here, 4,392 against 260, and an
    # unbalanced fit would push every probability toward zero and every weight
    # to the lower clip. Balancing makes the ratio a statement about which
    # compounds look test-like rather than about how few test compounds exist
    model = LogisticRegression(
        C=CLASSIFIER_C, max_iter=2000, class_weight="balanced", random_state=seed
    )

    # scored out of fold, not in sample. A linear model on 2,048 Morgan bits
    # over a few thousand compounds can nearly memorise the split, so an
    # in-sample AUC says only that it fitted. What the weight needs is whether
    # the two sets are separable at all, which is an out-of-fold question
    smallest = int(min(np.bincount(y.astype(int))))
    n_splits = min(5, smallest)
    if n_splits < 2:
        # too few of one class to hold any out, which happens only on toy
        # inputs; the weights below are still well defined
        auc = float("nan")
    else:
        folds = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)
        out_of_fold = cross_val_predict(model, x, y, cv=folds, method="predict_proba")[:, 1]
        auc = float(roc_auc_score(y, out_of_fold))

    model.fit(x, y)

    probability = model.predict_proba(x[: len(fit_smiles)])[:, 1]
    # guard the ratio against a probability of exactly one, which the clip
    # would otherwise never see because the division diverges first
    probability = np.clip(probability, 1e-6, 1 - 1e-6)
    weights = np.clip(probability / (1.0 - probability), low, high)
    return weights, auc


def fit_affine(
    out_of_fold: NDArray[np.float64],
    observed: NDArray[np.float64],
    weights: NDArray[np.float64] | None = None,
) -> tuple[float, float]:
    """Fit ``observed ~ slope * out_of_fold + intercept`` by weighted least squares.

    Parameters
    ----------
    out_of_fold : ndarray
        Predictions made by a model that did not train on the compound.
    observed : ndarray
        True labels, aligned with them.
    weights : ndarray or None, optional
        Per-compound weights. None fits unweighted, which is the ablation the
        density ratio is measured against.

    Returns
    -------
    slope, intercept : float

    Raises
    ------
    CalibrationError
        If the inputs disagree in length, hold fewer than two points, or the
        predictions are constant, which leaves the slope undetermined.
    """
    pred, truth, w = _aligned(out_of_fold, observed, weights)
    if pred.size < 2:
        raise CalibrationError("an affine map needs at least two points")
    if np.allclose(pred, pred[0]):
        raise CalibrationError("predictions are constant, so the slope is undetermined")

    design = np.column_stack([pred, np.ones_like(pred)])
    root = np.sqrt(w)
    solution, *_ = np.linalg.lstsq(design * root[:, None], truth * root, rcond=None)
    return float(solution[0]), float(solution[1])


def fit_scale(
    out_of_fold: NDArray[np.float64],
    observed: NDArray[np.float64],
    weights: NDArray[np.float64] | None = None,
) -> float:
    """Fit ``observed ~ factor * out_of_fold`` by weighted least squares.

    The affine map through the origin. Fitting the factor alone answers
    whether the offset was doing the work, and cannot introduce a bias of its
    own the way an intercept can: a model already unbiased in the mean is left
    unbiased by it.

    Parameters
    ----------
    out_of_fold : ndarray
        Predictions made by a model that did not train on the compound.
    observed : ndarray
        True labels, aligned with them.
    weights : ndarray or None, optional
        Per-compound weights. None fits unweighted.

    Returns
    -------
    float
        The factor.

    Raises
    ------
    CalibrationError
        If the inputs disagree in length, hold no points, or the predictions
        are all zero, which leaves the factor undetermined.
    """
    pred, truth, w = _aligned(out_of_fold, observed, weights)
    denominator = float(np.sum(w * pred * pred))
    if denominator == 0.0:
        raise CalibrationError("predictions are all zero, so the scale factor is undetermined")
    return float(np.sum(w * pred * truth) / denominator)


def fit_isotonic(
    out_of_fold: NDArray[np.float64],
    observed: NDArray[np.float64],
    weights: NDArray[np.float64] | None = None,
) -> tuple[tuple[float, ...], tuple[float, ...]]:
    """Fit a non-decreasing map by weighted isotonic regression.

    The most freedom any of these maps has, and the only one that can correct
    a curve. What it buys over the affine map is a question about this split
    rather than a general one: with a few thousand fit points the map is well
    determined in the middle of the range and thin at the ends, where it is
    fitted on the handful of compounds the model scores most extremely.

    Parameters
    ----------
    out_of_fold : ndarray
        Predictions made by a model that did not train on the compound.
    observed : ndarray
        True labels, aligned with them.
    weights : ndarray or None, optional
        Per-compound weights. None fits unweighted.

    Returns
    -------
    knots_x, knots_y : tuple of float
        The fitted step function, x increasing and y non-decreasing.

    Raises
    ------
    CalibrationError
        If the inputs disagree in length or hold fewer than two points.
    """
    from sklearn.isotonic import IsotonicRegression

    pred, truth, w = _aligned(out_of_fold, observed, weights)
    if pred.size < 2:
        raise CalibrationError("an isotonic map needs at least two points")

    fitted = IsotonicRegression(increasing=True, out_of_bounds="clip")
    fitted.fit(pred, truth, sample_weight=w)

    # the estimator keeps the knots it needs and nothing more, so the map is
    # recorded as those rather than as a value per fit compound
    x = np.asarray(fitted.X_thresholds_, dtype=np.float64)
    y = np.asarray(fitted.y_thresholds_, dtype=np.float64)
    return tuple(float(value) for value in x), tuple(float(value) for value in y)


def _aligned(
    out_of_fold: NDArray[np.float64],
    observed: NDArray[np.float64],
    weights: NDArray[np.float64] | None,
) -> tuple[NDArray[np.float64], NDArray[np.float64], NDArray[np.float64]]:
    """Return the three arrays a fit needs, checked against each other."""
    pred = np.asarray(out_of_fold, dtype=np.float64)
    truth = np.asarray(observed, dtype=np.float64)
    if pred.shape != truth.shape:
        raise CalibrationError(f"shape mismatch: {pred.shape} predictions, {truth.shape} labels")
    if pred.size == 0:
        raise CalibrationError("a calibration needs at least one point")

    w = np.ones_like(pred) if weights is None else np.asarray(weights, dtype=np.float64)
    if w.shape != pred.shape:
        raise CalibrationError(f"shape mismatch: {w.shape} weights, {pred.shape} predictions")
    return pred, truth, w


def summarize_weights(weights: NDArray[np.float64], clip: tuple[float, float]) -> dict[str, float]:
    """Return the weight distribution and how much of it the clip bound."""
    low, high = clip
    at_bound = np.isclose(weights, low) | np.isclose(weights, high)
    return {
        "min": float(weights.min()),
        "median": float(np.median(weights)),
        "max": float(weights.max()),
        "mean": float(weights.mean()),
        "clipped_fraction": float(at_bound.mean()),
    }


def calibrate(
    out_of_fold: NDArray[np.float64],
    observed: NDArray[np.float64],
    fit_smiles: list[str],
    test_smiles: list[str],
    *,
    method: str = "affine",
    radius: int = MORGAN_RADIUS,
    n_bits: int = MORGAN_BITS,
    clip: tuple[float, float] = WEIGHT_CLIP,
    weighted: bool = True,
    seed: int = 0,
) -> Calibration:
    """Fit a calibration from out-of-fold predictions, under the density ratio.

    The weighting is the report's and is the same whichever map is fitted, so
    the three methods differ in one thing only: how much freedom the map has.
    That is what makes them comparable, and what makes a flat result across all
    three an answer about this split rather than about a choice of map.

    Parameters
    ----------
    out_of_fold : ndarray
        One prediction per fit compound, made without that compound.
    observed : ndarray
        True labels for the fit compounds.
    fit_smiles, test_smiles : list of str
        Canonical SMILES for both sets, the fit list aligned with the arrays.
    method : str, optional
        Which map to fit, one of :data:`METHODS`. Defaults to the report's
        affine map.
    radius, n_bits, clip, seed : optional
        Passed to :func:`density_ratio_weights`.
    weighted : bool, optional
        False fits the map unweighted, which is the ablation that says what
        the density ratio bought. Defaults to True.

    Returns
    -------
    AffineCalibration or IsotonicCalibration
        The map, and the evidence behind it.

    Raises
    ------
    CalibrationError
        If the method is not one this module fits.
    """
    if method not in METHODS:
        raise CalibrationError(f"unknown calibration method {method!r}; known: {list(METHODS)}")

    if weighted:
        weights, auc = density_ratio_weights(
            fit_smiles, test_smiles, radius=radius, n_bits=n_bits, clip=clip, seed=seed
        )
    else:
        weights, auc = np.ones(len(fit_smiles)), float("nan")

    summary = summarize_weights(weights, clip)
    evidence = {
        "n_fit": int(np.size(out_of_fold)),
        "weight_summary": summary,
        "classifier_auc": auc,
    }

    if method == "isotonic":
        knots_x, knots_y = fit_isotonic(out_of_fold, observed, weights)
        logger.info(
            "isotonic calibration: %d knots over [%.3f, %.3f], separator AUC %.3f",
            len(knots_x),
            knots_x[0],
            knots_x[-1],
            auc,
        )
        return IsotonicCalibration(knots_x=knots_x, knots_y=knots_y, **evidence)

    if method == "scale":
        slope, intercept = fit_scale(out_of_fold, observed, weights), 0.0
    else:
        slope, intercept = fit_affine(out_of_fold, observed, weights)
    logger.info(
        "%s calibration: slope %.4f, intercept %.4f, separator AUC %.3f",
        method,
        slope,
        intercept,
        auc,
    )
    return AffineCalibration(slope=slope, intercept=intercept, method=method, **evidence)


def fold_indices(n: int, *, n_folds: int = N_FOLDS, seed: int = 0) -> list[tuple[Any, Any]]:
    """Return the train and held-out row indices for each fold.

    Shuffled with a fixed seed so the partition is a property of the seed and
    the row count rather than of the order the split file happened to be in.
    """
    if n_folds < 2:
        raise CalibrationError(f"out-of-fold predictions need at least 2 folds, got {n_folds}")
    if n_folds > n:
        raise CalibrationError(f"{n_folds} folds over {n} compounds")
    splitter = KFold(n_splits=n_folds, shuffle=True, random_state=seed)
    return list(splitter.split(np.arange(n)))
